Repository googleapis/python-logging, pull requests merged in 2020-10, with the labels that each got.

#70 fix: failing CI tests
  .kokoro/build.sh
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  docs/conf.py
  google/cloud/logging/entries.py
  google/cloud/logging/handlers/_helpers.py
  google/cloud/logging/logger.py
  google/cloud/logging_v2/gapic/config_service_v2_client.py
  google/cloud/logging_v2/gapic/logging_service_v2_client.py
  google/cloud/logging_v2/gapic/metrics_service_v2_client.py
  google/cloud/logging_v2/proto/log_entry_pb2.py
  google/cloud/logging_v2/proto/logging_config_pb2.py
  google/cloud/logging_v2/proto/logging_config_pb2_grpc.py
  google/cloud/logging_v2/proto/logging_metrics_pb2.py
  google/cloud/logging_v2/proto/logging_metrics_pb2_grpc.py
  google/cloud/logging_v2/proto/logging_pb2.py
  google/cloud/logging_v2/proto/logging_pb2_grpc.py
  noxfile.py
  scripts/decrypt-secrets.sh
  testing/.gitignore
  tests/system/test_system.py
  tests/unit/test__http.py
Labels: cla: yes

#73 fix: add default filter settings to list_entries
  google/cloud/logging/_helpers.py
  google/cloud/logging/client.py
  google/cloud/logging/logger.py
  noxfile.py
  tests/unit/test__helpers.py
  tests/unit/test_client.py
  tests/unit/test_logger.py
Labels: cla: yes, do not merge

#81 chore: add api-logging to codeowners
  .github/CODEOWNERS
  .repo-metadata.json
  CHANGELOG.md
  README.rst
  docs/client.rst
  docs/usage.rst
Labels: api: logging, cla: yes, lang: python, priority: p2, type: process

#78 refactor!: remove python2
  google/cloud/logging/handlers/_helpers.py
  google/cloud/logging/handlers/middleware/request.py
  noxfile.py
  setup.py
  tests/unit/handlers/test__helpers.py
Labels: cla: yes, lang: python, type: cleanup

#79 refactor: replace noxfile
  docs/conf.py
  google/cloud/logging_v2/gapic/config_service_v2_client.py
  google/cloud/logging_v2/gapic/logging_service_v2_client.py
  google/cloud/logging_v2/gapic/metrics_service_v2_client.py
  google/cloud/logging_v2/proto/log_entry_pb2.py
  google/cloud/logging_v2/proto/logging_config_pb2.py
  google/cloud/logging_v2/proto/logging_metrics_pb2.py
  google/cloud/logging_v2/proto/logging_pb2.py
  noxfile.py
  setup.py
  synth.py
  tests/unit/test_client.py
  tests/unit/test_logger.py
Labels: cla: yes, lang: python, type: cleanup

#83 fix: move manual code to logging_v2
  docs/client.rst
  docs/entries.rst
  docs/handlers-app-engine.rst
  docs/handlers-container-engine.rst
  docs/handlers.rst
  docs/logger.rst
  docs/metric.rst
  docs/sink.rst
  docs/transports-base.rst
  docs/transports-sync.rst
  docs/transports-thread.rst
  google/cloud/logging/__init__.py
  google/cloud/logging_v2/__init__.py
  google/cloud/logging_v2/_gapic.py
  google/cloud/logging_v2/_helpers.py
  google/cloud/logging_v2/_http.py
  google/cloud/logging_v2/client.py
  google/cloud/logging_v2/entries.py
  google/cloud/logging_v2/handlers/__init__.py
  google/cloud/logging_v2/handlers/_helpers.py
  google/cloud/logging_v2/handlers/app_engine.py
  google/cloud/logging_v2/handlers/container_engine.py
  google/cloud/logging_v2/handlers/handlers.py
  google/cloud/logging_v2/handlers/middleware/__init__.py
  google/cloud/logging_v2/handlers/middleware/request.py
  google/cloud/logging_v2/handlers/transports/__init__.py
  google/cloud/logging_v2/handlers/transports/background_thread.py
  google/cloud/logging_v2/handlers/transports/base.py
  google/cloud/logging_v2/handlers/transports/sync.py
  google/cloud/logging_v2/logger.py
  google/cloud/logging_v2/metric.py
  google/cloud/logging_v2/resource.py
  google/cloud/logging_v2/sink.py
  tests/system/gapic/v2/test_system_logging_service_v2_v2.py
  tests/system/test_system.py
  tests/unit/gapic/v2/test_config_service_v2_client_v2.py
  tests/unit/gapic/v2/test_logging_service_v2_client_v2.py
  tests/unit/gapic/v2/test_metrics_service_v2_client_v2.py
  tests/unit/handlers/middleware/test_request.py
  tests/unit/handlers/test__helpers.py
  tests/unit/handlers/test_app_engine.py
  tests/unit/handlers/test_container_engine.py
  tests/unit/handlers/test_handlers.py
  tests/unit/handlers/transports/test_background_thread.py
  tests/unit/handlers/transports/test_base.py
  tests/unit/handlers/transports/test_sync.py
  tests/unit/test__gapic.py
  tests/unit/test__helpers.py
  tests/unit/test__http.py
  tests/unit/test_client.py
  tests/unit/test_entries.py
  tests/unit/test_logger.py
  tests/unit/test_logging_shim.py
  tests/unit/test_metric.py
  tests/unit/test_sink.py
Labels: cla: yes
