Repository googleapis/python-logging, pull requests merged in 2020-02, with the labels that each got.

#2 chore: add split repo templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-please.yml
  .gitignore
  .kokoro/build.sh
  .kokoro/continuous/common.cfg
  .kokoro/continuous/continuous.cfg
  .kokoro/docs/common.cfg
  .kokoro/docs/docs.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/trampoline.sh
  .repo-metadata.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  LICENSE
  MANIFEST.in
  docs/conf.py
  noxfile.py
  renovate.json
  setup.py
  synth.metadata
  test_utils/credentials.json.enc
  test_utils/scripts/circleci/get_tagged_package.py
  test_utils/scripts/circleci/twine_upload.sh
  test_utils/scripts/get_target_packages.py
  test_utils/scripts/get_target_packages_kokoro.py
  test_utils/scripts/run_emulator.py
  test_utils/scripts/update_docs.sh
  test_utils/setup.py
  test_utils/test_utils/__init__.py
  test_utils/test_utils/imports.py
  test_utils/test_utils/retry.py
  test_utils/test_utils/system.py
  test_utils/test_utils/vpcsc_config.py
  tests/unit/test__http.py
Labels: cla: yes, type: process

#22 feat: add support for cmek settings; undeprecate resource name helper methods; bump copyright year to 2020
  google/cloud/logging_v2/gapic/config_service_v2_client.py
  google/cloud/logging_v2/gapic/config_service_v2_client_config.py
  google/cloud/logging_v2/gapic/enums.py
  google/cloud/logging_v2/gapic/logging_service_v2_client.py
  google/cloud/logging_v2/gapic/metrics_service_v2_client.py
  google/cloud/logging_v2/gapic/transports/config_service_v2_grpc_transport.py
  google/cloud/logging_v2/gapic/transports/logging_service_v2_grpc_transport.py
  google/cloud/logging_v2/gapic/transports/metrics_service_v2_grpc_transport.py
  google/cloud/logging_v2/proto/log_entry.proto
  google/cloud/logging_v2/proto/log_entry_pb2.py
  google/cloud/logging_v2/proto/logging.proto
  google/cloud/logging_v2/proto/logging_config.proto
  google/cloud/logging_v2/proto/logging_config_pb2.py
  google/cloud/logging_v2/proto/logging_config_pb2_grpc.py
  google/cloud/logging_v2/proto/logging_metrics.proto
  google/cloud/logging_v2/proto/logging_metrics_pb2.py
  google/cloud/logging_v2/proto/logging_pb2.py
  google/cloud/logging_v2/proto/logging_pb2_grpc.py
  synth.metadata
  tests/unit/gapic/v2/test_config_service_v2_client_v2.py
  tests/unit/gapic/v2/test_logging_service_v2_client_v2.py
  tests/unit/gapic/v2/test_metrics_service_v2_client_v2.py
Labels: cla: yes

#26 chore: change docstring line breaks (via synth)
  google/cloud/logging_v2/proto/logging_config_pb2.py
  synth.metadata
Labels: cla: yes

#28 test: drop majyk per-lang-version coverage level
  noxfile.py
Labels: cla: yes, testing, type: process
