Repository googleapis/python-logging, pull requests merged in 2021-01, with the labels that each got.

#145 chore: add constraints file
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
Labels: api: logging, cla: yes

#129 feat: allow modifying LogEntry data using extra argument
  google/cloud/logging_v2/handlers/app_engine.py
  google/cloud/logging_v2/handlers/handlers.py
  tests/system/test_system.py
  tests/unit/handlers/test_app_engine.py
  tests/unit/handlers/test_handlers.py
Labels: api: logging, cla: yes

#151 fix: add InternalServerError to list of expected errors
  tests/system/test_system.py
Labels: api: logging, cla: yes

#148 chore: Re-generated to pick up changes from synthtool.
  LICENSE
  docs/_static/custom.css
  synth.metadata
Labels: api: logging, cla: yes, context: full

#156 fix: use dict for http request
  google/cloud/logging_v2/handlers/_helpers.py
  tests/unit/handlers/test__helpers.py
Labels: api: logging, cla: yes

#161 test: reduced time filter length in system tests
  tests/system/test_system.py
Labels: api: logging, cla: yes

#160 fix: django content length extraction bug
  google/cloud/logging_v2/handlers/_helpers.py
  tests/unit/handlers/test__helpers.py
Labels: api: logging, cla: yes

#153 chore: Re-generated to pick up changes from synthtool.
  .kokoro/build.sh
  .kokoro/docs/docs-presubmit.cfg
  .trampolinerc
  noxfile.py
  synth.metadata
Labels: api: logging, cla: yes, context: full

#147 feat: add from_service_account_info factory and fix sphinx identifiers
  .coveragerc
  google/cloud/logging_v2/services/config_service_v2/async_client.py
  google/cloud/logging_v2/services/config_service_v2/client.py
  google/cloud/logging_v2/services/config_service_v2/pagers.py
  google/cloud/logging_v2/services/logging_service_v2/async_client.py
  google/cloud/logging_v2/services/logging_service_v2/client.py
  google/cloud/logging_v2/services/logging_service_v2/pagers.py
  google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  google/cloud/logging_v2/services/metrics_service_v2/client.py
  google/cloud/logging_v2/services/metrics_service_v2/pagers.py
  google/cloud/logging_v2/types/log_entry.py
  google/cloud/logging_v2/types/logging.py
  google/cloud/logging_v2/types/logging_config.py
  google/cloud/logging_v2/types/logging_metrics.py
  synth.metadata
  tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/unit/gapic/logging_v2/test_metrics_service_v2.py
Labels: api: logging, cla: yes, context: full

#146 chore: Re-generated to pick up changes from self.
  logging-v2-py.tar.gz
  synth.metadata
Labels: api: logging, cla: yes, context: none

#170 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: logging, automerge, cla: yes
