Repository googleapis/python-logging, pull requests merged in 2021-04, with the labels that each got.

#222 chore: Re-generated to pick up changes from self.
  logging-v2-py.tar.gz
  synth.metadata
Labels: api: logging, cla: yes, context: none

#248 chore: remove logging-v2-py.tar.gz from file tracking
  logging-v2-py.tar.gz
  synth.metadata
Labels: api: logging, cla: yes, context: none

#250 chore: use gcp-sphinx-docfx-yaml
  noxfile.py
  synth.metadata
Labels: api: logging, cla: yes, context: full

#253 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: logging, automerge, cla: yes, context: full

#259 chore: prevent normalization of semver versioning
  setup.py
Labels: api: logging, cla: yes

#260 chore: Re-generated to pick up changes from self.
  logging-v2-py.tar.gz
  synth.metadata
Labels: api: logging, cla: yes, context: none

#270 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/header-checker-lint.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  owlbot.py
  renovate.json
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: logging, cla: yes

#269 chore(revert): revert preventing normalization
  setup.py
Labels: api: logging, cla: yes
