Repository googleapis/python-logging, pull requests merged in 2022-04, with the labels that each got.

#512 chore: allow releases on previous majors
  .github/release-please.yml
  owlbot.py
Labels: api: logging, size: s

#511 chore: set up CI on v1 branch
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  noxfile.py
Labels: api: logging, size: m

#510 chore: set up CI on v2 branch
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/conf.py
  google/cloud/logging_v2/_gapic.py
  google/cloud/logging_v2/_http.py
  google/cloud/logging_v2/client.py
  google/cloud/logging_v2/handlers/transports/sync.py
  google/cloud/logging_v2/metric.py
  google/cloud/logging_v2/services/config_service_v2/async_client.py
  google/cloud/logging_v2/services/config_service_v2/client.py
  google/cloud/logging_v2/services/config_service_v2/transports/base.py
  google/cloud/logging_v2/services/config_service_v2/transports/grpc.py
  google/cloud/logging_v2/services/logging_service_v2/async_client.py
  google/cloud/logging_v2/services/logging_service_v2/client.py
  google/cloud/logging_v2/services/logging_service_v2/transports/base.py
  google/cloud/logging_v2/services/logging_service_v2/transports/grpc.py
  google/cloud/logging_v2/services/metrics_service_v2/async_client.py
  google/cloud/logging_v2/services/metrics_service_v2/client.py
  google/cloud/logging_v2/services/metrics_service_v2/transports/base.py
  google/cloud/logging_v2/services/metrics_service_v2/transports/grpc.py
  google/cloud/logging_v2/types/log_entry.py
  google/cloud/logging_v2/types/logging.py
  google/cloud/logging_v2/types/logging_config.py
  google/cloud/logging_v2/types/logging_metrics.py
  noxfile.py
  tests/unit/gapic/logging_v2/test_config_service_v2.py
  tests/unit/gapic/logging_v2/test_logging_service_v2.py
  tests/unit/gapic/logging_v2/test_metrics_service_v2.py
  tests/unit/handlers/test_handlers.py
  tests/unit/handlers/test_structured_log.py
  tests/unit/handlers/transports/test_background_thread.py
  tests/unit/test__gapic.py
  tests/unit/test_logger.py
Labels: api: logging, size: xl

#535 fix: Reenable staleness bot
  .github/auto-label.yaml
  owlbot.py
Labels: api: logging, size: xs

#541 docs: Add link to interactive walkthrough
  README.rst
  docs/_static/guide-me.svg
Labels: api: logging, size: m
