Repository googleapis/python-logging, pull requests merged in 2022-08, with the labels that each got.

#584 chore: update supported python versions in README
  README.rst
Labels: api: logging, size: xs

#595 test: add performance tests
  .kokoro/performance/common.cfg
  .kokoro/performance/presubmit.cfg
  .kokoro/test-performance.sh
  tests/performance/noxfile.py
  tests/performance/test_performance.py
Labels: api: logging, size: l

#598 chore: added extra variables to each kokoro config
  .kokoro/performance/common.cfg
Labels: api: logging, size: s

#600 fix(deps): allow protobuf < 5.0.0
  setup.py
  testing/constraints-3.7.txt
Labels: api: logging, automerge, size: xs

#603 chore: added extra variables owlbot kokoro configs
  .kokoro/common_env_vars.cfg
  .kokoro/continuous/common.cfg
  .kokoro/docs/common.cfg
  .kokoro/environment/appengine_flex_container/common.cfg
  .kokoro/environment/appengine_flex_python/common.cfg
  .kokoro/environment/appengine_standard/common.cfg
  .kokoro/environment/cloudrun/common.cfg
  .kokoro/environment/compute/common.cfg
  .kokoro/environment/functions/common.cfg
  .kokoro/environment/functions_37/common.cfg
  .kokoro/environment/kubernetes/common.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/release/common.cfg
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/python3.10/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.9/common.cfg
  owlbot.py
Labels: api: logging, size: l
