Repository googleapis/python-logging, pull requests merged in 2024-08, with the labels that each got.

#925 test: Added timestamp to sink names + autodelete sinks older than 2 hours in export_test.py
  samples/snippets/export_test.py
Labels: api: logging, size: s

#930 fix: Fixed type hinting issue with specifying Transport class
  google/cloud/logging_v2/handlers/handlers.py
Labels: api: logging, size: xs

#935 build: update constraints files
  CONTRIBUTING.rst
  noxfile.py
  owlbot.py
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.12.txt
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
  testing/constraints-3.9.txt
Labels: api: logging, size: m
