Repository googleapis/python-logging, pull requests merged in 2025-03, with the labels that each got.

#971 docs: Added documentation on log_level and excluded_loggers params in setup_logging
  docs/std-lib-integration.rst
  google/cloud/logging_v2/client.py
  google/cloud/logging_v2/handlers/handlers.py
  samples/snippets/usage_guide.py
Labels: api: logging, size: s

#976 chore: remove unused files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/requirements.in
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
  owlbot.py
Labels: api: logging, size: l

#972 docs: update README to break infinite redirect loop
  README.rst
Labels: api: logging, size: xs

#979 fix(deps): require google-cloud-audit-log >= 0.3.1
  setup.py
  testing/constraints-3.7.txt
  testing/constraints-3.8.txt
Labels: api: logging, size: xs

#917 feat: Added flushes/close functionality to logging handlers
  google/cloud/logging_v2/client.py
  google/cloud/logging_v2/handlers/handlers.py
  google/cloud/logging_v2/handlers/transports/background_thread.py
  google/cloud/logging_v2/handlers/transports/base.py
  google/cloud/logging_v2/handlers/transports/sync.py
  tests/system/test_system.py
  tests/unit/handlers/test_handlers.py
  tests/unit/handlers/transports/test_background_thread.py
  tests/unit/handlers/transports/test_base.py
  tests/unit/test_client.py
Labels: api: logging, stale: extraold, size: l
